# Module 18 Challenge - Citi Bikes
## Combine data by month for 5 years 2018 - 2023

In [71]:
# Imports , Pandas
import pandas as pd

In [72]:
# List of file names to be combined for 2019
files2019 = ['data/JC-201901-citibike-tripdata.csv', 
             'data/JC-201902-citibike-tripdata.csv', 
             'data/JC-201903-citibike-tripdata.csv', 
             'data/JC-201904-citibike-tripdata.csv', 
             'data/JC-201905-citibike-tripdata.csv', 
             'data/JC-201906-citibike-tripdata.csv', 
             'data/JC-201907-citibike-tripdata.csv', 
             'data/JC-201908-citibike-tripdata.csv', 
             'data/JC-201909-citibike-tripdata.csv', 
             'data/JC-201910-citibike-tripdata.csv', 
             'data/JC-201911-citibike-tripdata.csv', 
             'data/JC-201912-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df2019_list = []

# Loop through each file in the list
for file in files2019:
    # Read the file into a dataframe
    df2019 = pd.read_csv(file)

    # Append the dataframe to the list
    df2019_list.append(df2019)

# Concatenate all dataframes in the list into one dataframe
df2019 = pd.concat(df2019_list)
# Convert the 'starttime and endtime' columns to datetime datatype.
new_start = df2019.starttime
new_stop = df2019.stoptime
# convert objects to datetime
new_start = pd.to_datetime(new_start)
new_stop = pd.to_datetime(new_stop)
# add separate fields to DF for Start and stop dates & times
df2019['StartDate'] = new_start.dt.date 
df2019['StopDate'] = new_stop.dt.date 
df2019['StartTime'] = new_start.dt.time 
df2019['StopTime'] = new_stop.dt.time 
# Show dataframe
df2019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,StartDate,StopDate,StartTime,StopTime
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1,2019-01-01,2019-01-01,03:09:09.711000,03:12:30.879000
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2,2019-01-01,2019-01-01,05:18:00.106000,05:26:25.905000
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1,2019-01-01,2019-01-01,10:36:33.340000,10:49:10.260000
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0,2019-01-01,2019-01-01,12:43:38.643000,13:09:54.528000
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0,2019-01-01,2019-01-01,12:43:39.601000,13:09:46.510000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19723,283,2019-12-31 23:12:18.5480,2019-12-31 23:17:01.8740,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29245,Customer,1990,1,2019-12-31,2019-12-31,23:12:18.548000,23:17:01.874000
19724,267,2019-12-31 23:19:03.5840,2019-12-31 23:23:30.6640,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26153,Subscriber,1989,1,2019-12-31,2019-12-31,23:19:03.584000,23:23:30.664000
19725,379,2019-12-31 23:19:06.5830,2019-12-31 23:25:25.7970,3209,Brunswick St,40.724176,-74.050656,3185,City Hall,40.717732,-74.043845,26276,Subscriber,1984,1,2019-12-31,2019-12-31,23:19:06.583000,23:25:25.797000
19726,188,2019-12-31 23:24:00.2630,2019-12-31 23:27:09.0400,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,29461,Subscriber,1987,1,2019-12-31,2019-12-31,23:24:00.263000,23:27:09.040000
19727,326,2019-12-31 23:45:20.9780,2019-12-31 23:50:47.7490,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29123,Subscriber,1988,1,2019-12-31,2019-12-31,23:45:20.978000,23:50:47.749000

In [73]:
# create new df for tableau just the needed columns grouped by date for similar start & end points

df2019_cnt = pd.DataFrame(df2019.groupby(['StartDate', 
                                    'start station id', 
                                    'start station name', 
                                    'start station latitude', 
                                    'start station longitude',	
                                    'end station id',	
                                    'end station name']).size().reset_index(name='count') )
# adding a column for ride type
df2019_cnt ['ride type'] = 'classic_bike'
# Show dataframe
df2019_cnt

,StartDate,start station id,start station name,start station latitude,start station longitude,end station id,end station name,count,ride type
0,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,2,classic_bike
1,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,1,classic_bike
2,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3196,Riverview Park,2,classic_bike
3,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,2,classic_bike
4,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,1,classic_bike
...,...,...,...,...,...,...,...,...,...
173839,2019-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3279,Dixon Mills,1,classic_bike
173840,2019-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3638,Washington St,2,classic_bike
173841,2019-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,5,classic_bike
173842,2019-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3791,Hoboken Ave at Monmouth St,1,classic_bike
173843,2019-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3792,Columbus Dr at Exchange Pl,2,classic_bike

In [74]:
# List of file names to be combined for 2020
files2020 = ['data/JC-202001-citibike-tripdata.csv', 
             'data/JC-202002-citibike-tripdata.csv', 
             'data/JC-202003-citibike-tripdata.csv', 
             'data/JC-202004-citibike-tripdata.csv', 
             'data/JC-202005-citibike-tripdata.csv', 
             'data/JC-202006-citibike-tripdata.csv', 
             'data/JC-202007-citibike-tripdata.csv', 
             'data/JC-202008-citibike-tripdata.csv', 
             'data/JC-202009-citibike-tripdata.csv', 
             'data/JC-202010-citibike-tripdata.csv', 
             'data/JC-202011-citibike-tripdata.csv', 
             'data/JC-202012-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df2020_list = []

# Loop through each file in the list
for file in files2020:
    # Read the file into a dataframe
    df2020 = pd.read_csv(file)

    # Append the dataframe to the list
    df2020_list.append(df2020)

# Concatenate all dataframes in the list into one dataframe
df2020 = pd.concat(df2020_list)
# Convert the 'starttime and endtime' columns to datetime datatype.
new_start = df2020.starttime
new_stop = df2020.stoptime
# convert objects to datetime
new_start = pd.to_datetime(new_start)
new_stop = pd.to_datetime(new_stop)
# add separate fields to DF for Start and stop dates & times
df2020['StartDate'] = new_start.dt.date 
df2020['StopDate'] = new_stop.dt.date 
df2020['StartTime'] = new_start.dt.time 
df2020['StopTime'] = new_stop.dt.time 
# Show dataframe
df2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,StartDate,StopDate,StartTime,StopTime
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2,2020-01-01,2020-01-01,00:04:50.192000,00:08:37.037000
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2,2020-01-01,2020-01-01,00:16:01.670000,00:22:19.080000
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1,2020-01-01,2020-01-01,00:17:33.877000,00:22:22.442000
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0,2020-01-01,2020-01-01,00:32:05.902000,00:39:21.066000
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2,2020-01-01,2020-01-01,00:46:19.678000,00:50:11.344000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0,2020-12-31,2020-12-31,23:07:44.003000,23:36:54.471000
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0,2020-12-31,2020-12-31,23:18:00.263000,23:43:19.859000
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1,2020-12-31,2021-01-01,23:31:09.462000,00:00:31.329000
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0,2020-12-31,2020-12-31,23:35:45.464000,23:46:22.730000
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1,2020-12-31,2021-01-01,23:48:34.575000,00:15:22.309000

In [75]:
# create new df for tableau just the needed columns grouped by date for similar start & end points

df2020_cnt = pd.DataFrame(df2020.groupby(['StartDate', 
                                    'start station id', 
                                    'start station name', 
                                    'start station latitude', 
                                    'start station longitude',	
                                    'end station id',	
                                    'end station name']).size().reset_index(name='count') )
# adding a column for ride type
df2020_cnt ['ride type'] = 'classic_bike'
# Show dataframe
df2020_cnt

,StartDate,start station id,start station name,start station latitude,start station longitude,end station id,end station name,count,ride type
0,2020-01-01,3184,Paulus Hook,40.714145,-74.033552,3184,Paulus Hook,1,classic_bike
1,2020-01-01,3184,Paulus Hook,40.714145,-74.033552,3267,Morris Canal,1,classic_bike
2,2020-01-01,3184,Paulus Hook,40.714145,-74.033552,3275,Columbus Drive,1,classic_bike
3,2020-01-01,3184,Paulus Hook,40.714145,-74.033552,3639,Harborside,2,classic_bike
4,2020-01-01,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,1,classic_bike
...,...,...,...,...,...,...,...,...,...
162821,2020-12-31,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,3638,Washington St,2,classic_bike
162822,2020-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3209,Brunswick St,1,classic_bike
162823,2020-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3267,Morris Canal,1,classic_bike
162824,2020-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3276,Marin Light Rail,1,classic_bike
162825,2020-12-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,2,classic_bike

In [76]:
# January is trhe old format
# Create an empty list to store each dataframe
df2021jan_list = []

# Read the file into a dataframe
df2021jan = pd.read_csv('data/JC-202101-citibike-tripdata.csv')

# Append the dataframe to the list
df2021jan_list.append(df2021jan)

# Concatenate all dataframes in the list into one dataframe
df2021jan = pd.concat(df2021jan_list)
# Convert the 'starttime and endtime' columns to datetime datatype.
new_start = df2021jan.starttime
new_stop = df2021jan.stoptime
# convert objects to datetime
new_start = pd.to_datetime(new_start)
new_stop = pd.to_datetime(new_stop)
# add separate fields to DF for Start and stop dates & times
df2021jan['StartDate'] = new_start.dt.date 
df2021jan['StopDate'] = new_stop.dt.date 
df2021jan['StartTime'] = new_start.dt.time 
df2021jan['StopTime'] = new_stop.dt.time 
# Show dataframe
df2021jan

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,StartDate,StopDate,StartTime,StopTime
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,2021-01-01,2021-01-01,00:03:35.510000,00:08:01.777000
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2,2021-01-01,2021-01-01,00:23:32.925000,00:49:16.083000
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1,2021-01-01,2021-01-01,00:23:50.794000,00:48:12.566000
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0,2021-01-01,2021-01-01,00:31:09.077000,00:44:22.943000
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0,2021-01-01,2021-01-01,00:35:52.190000,00:45:48.774000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1,2021-01-31,2021-01-31,20:16:05.470000,20:57:22.011000
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1,2021-01-31,2021-01-31,21:05:05.209000,21:07:32.866000
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2,2021-01-31,2021-01-31,21:06:23.588000,21:17:23.842000
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1,2021-01-31,2021-01-31,21:16:37.822000,21:23:02.124000
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1,2021-01-31,2021-01-31,23:24:50.881000,23:30:47.303000

In [77]:
# create new df for tableau just the needed columns grouped by date for similar start & end points

df2021jan_cnt = pd.DataFrame(df2021jan.groupby(['StartDate', 
                                    'start station id', 
                                    'start station name', 
                                    'start station latitude', 
                                    'start station longitude',	
                                    'end station id',	
                                    'end station name']).size().reset_index(name='count') )
# adding a column for ride type
df2021jan_cnt ['ride type'] = 'classic_bike'
# Show dataframe
df2021jan_cnt

,StartDate,start station id,start station name,start station latitude,start station longitude,end station id,end station name,count,ride type
0,2021-01-01,3184,Paulus Hook,40.714145,-74.033552,3267,Morris Canal,2,classic_bike
1,2021-01-01,3184,Paulus Hook,40.714145,-74.033552,3638,Washington St,2,classic_bike
2,2021-01-01,3185,City Hall,40.717732,-74.043845,3184,Paulus Hook,1,classic_bike
3,2021-01-01,3185,City Hall,40.717732,-74.043845,3192,Liberty Light Rail,1,classic_bike
4,2021-01-01,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,1,classic_bike
...,...,...,...,...,...,...,...,...,...
7944,2021-01-31,3681,Grand St,40.715178,-74.037683,3681,Grand St,1,classic_bike
7945,2021-01-31,3681,Grand St,40.715178,-74.037683,3792,Columbus Dr at Exchange Pl,1,classic_bike
7946,2021-01-31,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,3202,Newport PATH,1,classic_bike
7947,2021-01-31,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,3677,Glenwood Ave,1,classic_bike
7948,2021-01-31,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3267,Morris Canal,2,classic_bike

In [78]:
# List of file names to be combined for 2021
files2021 = ['data/JC-202102-citibike-tripdata.csv', 
             'data/JC-202103-citibike-tripdata.csv', 
             'data/JC-202104-citibike-tripdata.csv', 
             'data/JC-202105-citibike-tripdata.csv', 
             'data/JC-202106-citibike-tripdata.csv', 
             'data/JC-202107-citibike-tripdata.csv', 
             'data/JC-202108-citibike-tripdata.csv', 
             'data/JC-202109-citibike-tripdata.csv', 
             'data/JC-202110-citibike-tripdata.csv', 
             'data/JC-202111-citibike-tripdata.csv', 
             'data/JC-202112-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df2021_list = []

# Loop through each file in the list
for file in files2021:
    # Read the file into a dataframe
    df2021 = pd.read_csv(file)

    # Append the dataframe to the list
    df2021_list.append(df2021)

# Concatenate all dataframes in the list into one dataframe
df2021 = pd.concat(df2021_list)
# Convert the 'Started_at and ended_at' columns to datetime datatype.
new_start = df2021.started_at
new_stop = df2021.ended_at
# convert objects to datetime
new_start = pd.to_datetime(new_start)
new_stop = pd.to_datetime(new_stop)
# add separate fields to DF for Start and stop dates & times
df2021['StartDate'] = new_start.dt.date 
df2021['StopDate'] = new_stop.dt.date 
df2021['StartTime'] = new_start.dt.time 
df2021['StopTime'] = new_stop.dt.time 
# Show dataframe
df2021

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,StartDate,StopDate,StartTime,StopTime
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member,2021-02-03,2021-02-03,23:11:28,23:18:28
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member,2021-02-27,2021-02-27,16:34:05,16:56:40
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member,2021-02-26,2021-02-26,23:16:04,23:22:25
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual,2021-02-24,2021-02-24,16:51:50,17:16:09
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member,2021-02-24,2021-02-24,20:44:16,20:44:46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48016,13FE513C650901A3,classic_bike,2021-12-16 17:17:46,2021-12-16 17:22:53,Grove St PATH,JC005,Hamilton Park,JC009,40.719586,-74.043117,40.727596,-74.044247,member,2021-12-16,2021-12-16,17:17:46,17:22:53
48017,CA29051F38E67D30,classic_bike,2021-12-07 17:10:29,2021-12-07 17:15:02,Grove St PATH,JC005,Hamilton Park,JC009,40.719586,-74.043117,40.727596,-74.044247,member,2021-12-07,2021-12-07,17:10:29,17:15:02
48018,A719DEA143005404,classic_bike,2021-12-18 09:50:14,2021-12-18 09:55:55,Grove St PATH,JC005,Hamilton Park,JC009,40.719586,-74.043117,40.727596,-74.044247,member,2021-12-18,2021-12-18,09:50:14,09:55:55
48019,D39126975208B59D,classic_bike,2021-12-10 21:43:32,2021-12-10 21:49:04,Grove St PATH,JC005,Hamilton Park,JC009,40.719586,-74.043117,40.727596,-74.044247,member,2021-12-10,2021-12-10,21:43:32,21:49:04
48020,1BB5CF43B5DF7E05,classic_bike,2021-12-08 11:09:56,2021-12-08 11:14:58,Hilltop,JC019,Hamilton Park,JC009,40.731169,-74.057574,40.727596,-74.044247,member,2021-12-08,2021-12-08,11:09:56,11:14:58

In [79]:
# create new df for tableau just the needed columns grouped by date for similar start & end points

# create new df for tableau just the needed columns grouped by date for similar start & end points
df2021bal_cnt = df2021.groupby(['StartDate', 
                             'start_station_id', 
                             'start_station_name', 
                             'start_lat',
                             'start_lng',	
                             'end_station_id',	
                             'end_station_name',
                             'rideable_type']).size().reset_index(name='count') 

# renaming columns to old names
df2021bal_cnt = df2021bal_cnt.rename(columns={ 
                                'start_station_id' : 'start station id', 
                                'start_station_name' : 'start station name', 
                                'start_lat' : 'start station latitude', 
                                'start_lng' : 'start station longitude',	
                                'end_station_id' : 'end station id',	
                                'end_station_name' :'end station name',
                                'rideable_type'  : 'ride type', 
                                'count': 'count'
})

# concatinate jan 2021 to the rest of the 2021 data
df2021_cnt = pd.concat([df2021jan_cnt, df2021bal_cnt], axis=0)


# Show dataframe
df2021_cnt

,StartDate,start station id,start station name,start station latitude,start station longitude,end station id,end station name,count,ride type
0,2021-01-01,3184,Paulus Hook,40.714145,-74.033552,3267,Morris Canal,2,classic_bike
1,2021-01-01,3184,Paulus Hook,40.714145,-74.033552,3638,Washington St,2,classic_bike
2,2021-01-01,3185,City Hall,40.717732,-74.043845,3184,Paulus Hook,1,classic_bike
3,2021-01-01,3185,City Hall,40.717732,-74.043845,3192,Liberty Light Rail,1,classic_bike
4,2021-01-01,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,1,classic_bike
...,...,...,...,...,...,...,...,...,...
342553,2021-12-31,JC106,Columbus Dr at Exchange Pl,40.716870,-74.032810,JC098,Washington St,1,classic_bike
342554,2021-12-31,JC106,Columbus Dr at Exchange Pl,40.716870,-74.032810,JC098,Washington St,1,electric_bike
342555,2021-12-31,JC106,Columbus Dr at Exchange Pl,40.716870,-74.032810,JC104,Harborside,2,classic_bike
342556,2021-12-31,JC106,Columbus Dr at Exchange Pl,40.716870,-74.032810,JC106,Columbus Dr at Exchange Pl,4,classic_bike
342557,2021-12-31,JC107,Grant Ave & MLK Dr,40.709198,-74.080843,JC051,Union St,1,electric_bike

In [80]:
# List of file names to be combined for 2022
files2022 = ['data/JC-202201-citibike-tripdata.csv', 
             'data/JC-202202-citibike-tripdata.csv', 
             'data/JC-202203-citibike-tripdata.csv', 
             'data/JC-202204-citibike-tripdata.csv', 
             'data/JC-202205-citibike-tripdata.csv', 
             'data/JC-202206-citibike-tripdata.csv', 
             'data/JC-202207-citibike-tripdata.csv', 
             'data/JC-202208-citibike-tripdata.csv', 
             'data/JC-202209-citibike-tripdata.csv', 
             'data/JC-202210-citibike-tripdata.csv', 
             'data/JC-202211-citibike-tripdata.csv', 
             'data/JC-202212-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df2022_list = []

# Loop through each file in the list
for file in files2022:
    # Read the file into a dataframe
    df2022 = pd.read_csv(file)

    # Append the dataframe to the list
    df2022_list.append(df2022)

# Concatenate all dataframes in the list into one dataframe
df2022 = pd.concat(df2022_list)
# Convert the 'Started_at and ended_at' columns to datetime datatype.
new_start = df2022.started_at
new_stop = df2022.ended_at
# convert objects to datetime
new_start = pd.to_datetime(new_start)
new_stop = pd.to_datetime(new_stop)
# add separate fields to DF for Start and stop dates & times
df2022['StartDate'] = new_start.dt.date 
df2022['StopDate'] = new_stop.dt.date 
df2022['StartTime'] = new_start.dt.time 
df2022['StopTime'] = new_stop.dt.time 
# Show dataframe
df2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,StartDate,StopDate,StartTime,StopTime
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member,2022-01-26,2022-01-26,18:50:39,18:51:53
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member,2022-01-28,2022-01-28,13:14:07,13:20:23
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member,2022-01-10,2022-01-10,19:55:13,20:00:37
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member,2022-01-26,2022-01-26,07:54:57,07:55:22
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member,2022-01-13,2022-01-13,18:44:46,18:45:43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48580,D438F1622839AC50,classic_bike,2022-12-06 15:43:38,2022-12-06 15:53:57,Dey St,JC065,Riverview Park,JC057,40.737828,-74.067083,40.744319,-74.043991,member,2022-12-06,2022-12-06,15:43:38,15:53:57
48581,747A63A8E782D171,electric_bike,2022-12-08 08:17:51,2022-12-08 08:23:33,9 St HBLR - Jackson St & 8 St,HB305,City Hall - Washington St & 1 St,HB105,40.747907,-74.038412,40.737360,-74.030970,casual,2022-12-08,2022-12-08,08:17:51,08:23:33
48582,AE090858CFDE6E82,electric_bike,2022-12-23 14:10:07,2022-12-23 14:14:18,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743140,-74.040041,40.737360,-74.030970,member,2022-12-23,2022-12-23,14:10:07,14:14:18
48583,B3CC8E70AF4E259C,classic_bike,2022-12-02 04:43:25,2022-12-02 04:46:55,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743135,-74.040080,40.737360,-74.030970,member,2022-12-02,2022-12-02,04:43:25,04:46:55
48584,176B601F21327350,classic_bike,2022-12-30 14:50:17,2022-12-30 14:55:37,14 St Ferry - 14 St & Shipyard Ln,HB202,City Hall - Washington St & 1 St,HB105,40.752747,-74.024035,40.737360,-74.030970,member,2022-12-30,2022-12-30,14:50:17,14:55:37

In [81]:
# create new df for tableau just the needed columns grouped by date for similar start & end points
df2022_cnt = df2022.groupby(['StartDate', 
                             'start_station_id', 
                             'start_station_name', 
                             'start_lat',
                             'start_lng',	
                             'end_station_id',	
                             'end_station_name',
                             'rideable_type']).size().reset_index(name='count')  

# renaming columns to old names
df2022_cnt = df2022_cnt.rename(columns={ 
                                'start_station_id' : 'start station id', 
                                'start_station_name' : 'start station name', 
                                'start_lat' : 'start station latitude', 
                                'start_lng' : 'start station longitude',	
                                'end_station_id' : 'end station id',	
                                'end_station_name' :'end station name',
                                'count' : 'count',
                                'rideable_type' : 'ride type' 
})

# Show dataframe
df2022_cnt

,StartDate,start station id,start station name,start station latitude,start station longitude,end station id,end station name,ride type,count
0,2022-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,HB101,Hoboken Terminal - Hudson St & Hudson Pl,classic_bike,1
1,2022-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,HB203,Bloomfield St & 15 St,electric_bike,1
2,2022-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,HB304,7 St & Monroe St,electric_bike,1
3,2022-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,HB404,Mama Johnson Field - 4 St & Jackson St,electric_bike,1
4,2022-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,HB407,Adams St & 2 St,classic_bike,4
...,...,...,...,...,...,...,...,...,...
583355,2022-12-31,JC115,Grove St PATH,40.719410,-74.043090,JC102,Grand St,classic_bike,1
583356,2022-12-31,JC115,Grove St PATH,40.719410,-74.043090,JC102,Grand St,electric_bike,2
583357,2022-12-31,JC115,Grove St PATH,40.719410,-74.043090,JC103,Journal Square,classic_bike,1
583358,2022-12-31,JC115,Grove St PATH,40.719410,-74.043090,JC110,JC Medical Center,classic_bike,1
583359,2022-12-31,JC115,Grove St PATH,40.719410,-74.043090,JC110,JC Medical Center,electric_bike,1

In [82]:
# List of file names to be combined for 2023
files2023 = ['data/JC-202301-citibike-tripdata.csv', 
             'data/JC-202302-citibike-tripdata.csv', 
             'data/JC-202303-citibike-tripdata.csv', 
             'data/JC-202304-citibike-tripdata.csv', 
             'data/JC-202305-citibike-tripdata.csv', 
             'data/JC-202306-citibike-tripdata.csv', 
             'data/JC-202307-citibike-tripdata.csv', 
             'data/JC-202308-citibike-tripdata.csv', 
             'data/JC-202309-citibike-tripdata.csv', 
             'data/JC-202310-citibike-tripdata.csv', 
             'data/JC-202311-citibike-tripdata.csv', 
             'data/JC-202312-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df2023_list = []

# Loop through each file in the list
for file in files2023:
    # Read the file into a dataframe
    df2023 = pd.read_csv(file)

    # Append the dataframe to the list
    df2023_list.append(df2023)

# Concatenate all dataframes in the list into one dataframe
df2023 = pd.concat(df2023_list)
# Convert the 'Started_at and ended_at' columns to datetime datatype.
new_start = df2023.started_at
new_stop = df2023.ended_at
# convert objects to datetime
new_start = pd.to_datetime(new_start)
new_stop = pd.to_datetime(new_stop)
# add separate fields to DF for Start and stop dates & times
df2023['StartDate'] = new_start.dt.date 
df2023['StopDate'] = new_stop.dt.date 
df2023['StartTime'] = new_start.dt.time 
df2023['StopTime'] = new_stop.dt.time 
# Show dataframe
df2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,StartDate,StopDate,StartTime,StopTime
0,0905B18B365C9D20,classic_bike,2023-01-28 09:18:10,2023-01-28 09:28:52,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735938,-74.030305,40.727596,-74.044247,member,2023-01-28,2023-01-28,09:18:10,09:28:52
1,B4F0562B05CB5404,electric_bike,2023-01-23 20:10:12,2023-01-23 20:18:27,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Southwest Park - Jackson St & Observer Hwy,HB401,40.735938,-74.030305,40.737551,-74.041664,member,2023-01-23,2023-01-23,20:10:12,20:18:27
2,5ABF032895F5D87E,classic_bike,2023-01-29 15:27:04,2023-01-29 15:32:38,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Marshall St & 2 St,HB408,40.735944,-74.030383,40.740802,-74.042521,member,2023-01-29,2023-01-29,15:27:04,15:32:38
3,E7E1F9C53976D2F9,classic_bike,2023-01-24 18:35:08,2023-01-24 18:42:13,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735986,-74.030364,40.727596,-74.044247,member,2023-01-24,2023-01-24,18:35:08,18:42:13
4,323165780CA0734B,classic_bike,2023-01-21 20:44:09,2023-01-21 20:48:08,Hamilton Park,JC009,Manila & 1st,JC082,40.727596,-74.044247,40.721651,-74.042884,member,2023-01-21,2023-01-21,20:44:09,20:48:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58675,7E862701EE7A6A03,classic_bike,2023-12-20 17:55:41,2023-12-20 18:00:10,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748720,-74.040487,40.754530,-74.026580,casual,2023-12-20,2023-12-20,17:55:41,18:00:10
58676,DFAF91AB91BE25DB,classic_bike,2023-12-13 14:36:43,2023-12-13 14:42:31,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748767,-74.040470,40.754530,-74.026580,member,2023-12-13,2023-12-13,14:36:43,14:42:31
58677,AEE7B49E6EDFAE6F,classic_bike,2023-12-18 16:40:00,2023-12-18 16:45:45,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744291,-74.034404,40.754530,-74.026580,member,2023-12-18,2023-12-18,16:40:00,16:45:45
58678,A38E98956AD72EFB,classic_bike,2023-12-02 13:42:51,2023-12-02 13:50:42,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744398,-74.034501,40.754530,-74.026580,member,2023-12-02,2023-12-02,13:42:51,13:50:42
58679,F16E0B969D877368,classic_bike,2023-12-19 16:30:13,2023-12-19 16:36:54,6 St & Grand St,HB302,Clinton St & 7 St,HB303,40.744398,-74.034501,40.745420,-74.033320,member,2023-12-19,2023-12-19,16:30:13,16:36:54

In [88]:
# create new df for tableau just the needed columns grouped by date for similar start & end points
df2023_cnt = df2023.groupby(['StartDate', 
                             'start_station_id', 
                             'start_station_name', 
                             'start_lat',
                             'start_lng',	
                             'end_station_id',	
                             'end_station_name', 
                             'rideable_type']).size().reset_index(name='count')  

# renaming columns to old names
df2023_cnt = df2023_cnt.rename(columns={ 
                                'start_station_id' : 'start station id', 
                                'start_station_name' : 'start station name', 
                                'start_lat' : 'start station latitude', 
                                'start_lng' : 'start station longitude',	
                                'end_station_id' : 'end station id',	
                                'end_station_name' :'end station name',
                                 'count' : 'count', 
                                'rideable_type' : 'ride type'       
                                                       
})

# Show dataframe
df2023_cnt

,StartDate,start station id,start station name,start station latitude,start station longitude,end station id,end station name,ride type,count
0,2023-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735853,-74.030364,JC105,Hoboken Ave at Monmouth St,classic_bike,1
1,2023-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735864,-74.030364,JC082,Manila & 1st,classic_bike,1
2,2023-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735878,-74.030360,JC105,Hoboken Ave at Monmouth St,classic_bike,1
3,2023-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735910,-74.030357,HB302,6 St & Grand St,classic_bike,1
4,2023-01-01,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735921,-74.030378,HB505,Willow Ave & 12 St,classic_bike,1
...,...,...,...,...,...,...,...,...,...
757677,2023-12-31,JC116,Exchange Pl,40.716504,-74.034399,JC072,Morris Canal,classic_bike,1
757678,2023-12-31,JC116,Exchange Pl,40.716527,-74.034534,HB102,Hoboken Terminal - River St & Hudson Pl,classic_bike,1
757679,2023-12-31,JC116,Exchange Pl,40.716541,-74.034356,HB501,Columbus Park - Clinton St & 9 St,classic_bike,1
757680,2023-12-31,JC116,Exchange Pl,40.716565,-74.034460,JC115,Grove St PATH,classic_bike,1
757681,2023-12-31,JC116,Exchange Pl,40.716606,-74.034390,JC006,Warren St,classic_bike,1

In [84]:
# Concatenate all dataframes for all the years into one dataframe  
df_5years = pd.concat([df2019_cnt, df2020_cnt, df2021_cnt, df2022_cnt, df2023_cnt], axis=0)

# Display the results
df_5years

,StartDate,start station id,start station name,start station latitude,start station longitude,end station id,end station name,count,ride type
0,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,2,classic_bike
1,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,1,classic_bike
2,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3196,Riverview Park,2,classic_bike
3,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,2,classic_bike
4,2019-01-01,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,1,classic_bike
...,...,...,...,...,...,...,...,...,...
757677,2023-12-31,JC116,Exchange Pl,40.716504,-74.034399,JC072,Morris Canal,1,classic_bike
757678,2023-12-31,JC116,Exchange Pl,40.716527,-74.034534,HB102,Hoboken Terminal - River St & Hudson Pl,1,classic_bike
757679,2023-12-31,JC116,Exchange Pl,40.716541,-74.034356,HB501,Columbus Park - Clinton St & 9 St,1,classic_bike
757680,2023-12-31,JC116,Exchange Pl,40.716565,-74.034460,JC115,Grove St PATH,1,classic_bike
757681,2023-12-31,JC116,Exchange Pl,40.716606,-74.034390,JC006,Warren St,1,classic_bike

In [85]:
# Save the combined dataframe to a CSV file to be used in Tableau
df_5years.to_csv('data for Tableau/citibike_5years.csv', index=False)

In [86]:
# Save the 2023 dataframe to a CSV file to be used in Tableau
df2023.to_csv('data for Tableau/citibike_2023.csv', index=False)